encoding: utf-8

# SEO相关信息
title: XiaoYu
description: XiaoYu的个人博客
keywords: TMaize,Blog,Java,Html,JavaScript
author: iiAuAiio
footerText: 'By XiaoYu'

# 这些不要动
permalink: /posts/:year/:month/:day/:title.html
kramdown:
  auto_ids: true
  input: GFM
  syntax_highlighter: rouge
exclude: ['CNAME', 'README.md', 'LICENSE', '_site', 'dist', 'Gemfile', 'Gemfile.lock', 'blog.sh']

# 域名配置
# baseurl配置,如果网站部署在根目录下的其他目录中，请设置为 /目录名
domainUrl: '暂未设置'
baseurl: ''

# 吐个槽地址，会在chat页面中重定向到该地址
tucaoUrl: http://qm.qq.com/cgi-bin/qm/qr?_wv=1027&k=miTCFKUcBldF3AjsO5vFGJEsVOPhR-Ix&authKey=lgi9nqPwOmIFM2ZqWKP5s7WOHkaPvo%2F6ln5k9P82MbOU8jr857PGntEpVillP2jG&noverify=0&group_code=716951248

# 菜单
# 必填字段 title: '文本' url: '链接'
# 可选字段 target: '_blank' 新页面打开 
menu:
  - title: 首页
    url: /
  - title: GTASA ENB
    url: /pages/GTASA_ENB.html
  - title: 工具
    url: /pages/GTASA_Tools.html
  - title: SAMP插件
    url: /pages/Scripts.html
  - title: 分类
    url: /pages/categories.html
  - title: 搜索
    url: /pages/search.html
  - title: 友链
    url: /pages/links.html
  - title: 留言
    url: /pages/chat.html
  - title: 关于
    url: /pages/about.html

# 点击页面文字冒出特效,不需要请设置为false
extClickEffect: true

# Google Adsense,不需要请设置为false
# _includes/ext-adsense.html 里面修改为自己的配置
extAdsense: false

# 数学公式支持，比较影响加载速度,不需要请设置为false
extMath: false

# 显示访问量统计，由不蒜子提供服务
extCount: false

# 友情链接
links:
  - title: 关于我个人哔哩哔哩账号
    url: https://b23.tv/KyOCVEi
  - title: QQ群
    url: http://qm.qq.com/cgi-bin/qm/qr?_wv=1027&k=miTCFKUcBldF3AjsO5vFGJEsVOPhR-Ix&authKey=lgi9nqPwOmIFM2ZqWKP5s7WOHkaPvo%2F6ln5k9P82MbOU8jr857PGntEpVillP2jG&noverify=0&group_code=716951248
